// user field constant
const emailFieldName = 'email';
const userIdFieldName = 'user_id';
const fullNameFieldName = 'full_name';
const profileUrlFieldName = 'profile_url';
const userNameFieldName = 'user_name';
const followingFieldName = 'following';
const followerFieldName = 'follower';
const professionFieldName = 'profession';
const descriptionFieldName = 'description';

// post field constant
const postIdFieldName = 'post_id';
const postUrlFieldName = 'post_url';
const publishedTimeFieldName = 'published_time';
const likesFieldName = 'likes';
const captionFieldName = 'caption';

// comment field constant
const commentIdFieldName = 'comment_id';
const commentTextFieldName = 'comment_text';

// gig field constant
const gigIdFieldName = 'gig_id';
const gigRatingFieldName = 'gig_rating';
const gigCoverUrlFieldName = 'gig_cover_url';
const gigTitleFieldName = 'gig_title';
const orderByFieldName = 'order_by';
const gigCategoryFieldName = 'gig_category';
const gigDescriptionFieldName = 'gig_description';
const teamMembersFieldName = 'team_members';
const serviceSpecificationsFieldName = 'service_specifications';
const gigStartingPriceFieldName = 'gig_starting_price';
const deliveryTimeFieldName = 'delivery_time';
const createdAtFieldName = 'created_at';

// order field constant
const orderIdFieldName = 'order_id';
const orderUserIdFieldName = 'order_user_id';
const orderUserFieldName = 'order_user';
const employerIdFieldName = 'employer_id';
const employerNameFieldName = 'employer_name';
const employerProfileUrlFieldName = 'employer_profile_url';
const projectRequirementFieldName = 'project_requirement';
const gigPriceFieldName = 'gig_price';
const serviceChargeFieldName = 'service_charge';
const totalPriceFieldName = 'total_price';
const filePathUrlFieldName = 'file_path';
const isOrderAcceptedFieldName = 'is_order_accepted';
const isOrderRejectedFieldName = 'is_order_rejected';
const deliveryMessageFieldName = 'delivery_message';
const isDeliveredFieldName = 'is_delivered';
const isDeliveryAcceptedFieldName = 'is_delivery_accepted';

// message feild constant
const messageIdFieldName = 'message_Id';
const sendByFieldName = 'send_by';
const messageTextFieldName = 'message_text';
const sendAtFieldName = 'send_at';
